name: Cache Next Build

description: Builds the Next.js app and caches the result

branding:
  color: yellow
  icon: cpu
runs:
  using: "composite"
  steps:
    # - name: Cache build
    #   id: build-cache
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ${{ github.workspace }}/.next
    #     key: build-${{ hashFiles('**/.env','**/*.lock','**/*.[jt]s*') }}

    # Builds the app if the cache was broken
    # NOTE: The .env file is added as a path to the build-cache so when
    # yarn build runs, it will have the proper environment variables
    - name: Build app
      # if: steps.build-cache.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
